version: "3.7"
services:
  db:
    build:
      context: db/    
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=$POSTGRES_SUPER_USER
      - POSTGRES_PASSWORD=$POSTGRES_SUPER_USER_PASSWORD
      - POSTGRES_DB
      - POSTGRES_ANONYMOUS_USER
      - POSTGRES_KNOWN_USER     
  server:
    init: true
    build:
      context: server/
      target: development
    environment:
      - DATABASE_URL=postgres://$POSTGRES_SUPER_USER:$POSTGRES_SUPER_USER_PASSWORD@db:5432/$POSTGRES_DB
      - JWT_SECRET
      - POSTGRES_ANONYMOUS_USER
      - POSTGRES_KNOWN_USER    
    links:
      - db    
  web:
    init: true
    build:
      context: web/
      target: development
      args:
        # Reminder: build args do not use env_file so they must be sourced manually (or exist in .env file) when running doker-compose.
        API_URL: //$HOST_NAME:$API_PORT
    links:
      - server
